Problem Description: Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
  
#include <stdio.h>
int main()
{
    int first=1; //intializing variable first with value 1 
    int second=2; //initializing variable second with value 2
    int sum; //declaring a variable sum, which adds first and second variable
    int even_sum=0; //initializing variable even_sum to 0 initially.
    while(first <= 4000000) //the Fibonacci sequence should not exceed 4million
    {
        printf("%d ",first); //printing first value 
        if(first%2==0) //checking if the variable first is even
        {
            even_sum=even_sum+first; //updating even_sum if the first variable is even
        }
        sum=first+second; 
        first=second; //swapping first with second variable
        second=sum; //swapping second with sum variable

        count--;
    }
    printf("\nThe sum of even fibbonacci numbers is: %d\n", even_sum); //printing even sum
    return 0;
}
